// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7aJAAFNFQkC_ut04JXvWFkyw4N6QZbsQ',
    appId: '1:1073180398990:web:8ef3a2ae19b59bc27700df',
    messagingSenderId: '1073180398990',
    projectId: 'peerpedia-777a2',
    authDomain: 'peerpedia-777a2.firebaseapp.com',
    storageBucket: 'peerpedia-777a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf7L8E9WpNUakjH11qvNpFcSr0NUZRF_A',
    appId: '1:1073180398990:android:45b7dcba6a4fe22f7700df',
    messagingSenderId: '1073180398990',
    projectId: 'peerpedia-777a2',
    storageBucket: 'peerpedia-777a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBut1jf80ZyGX840VcuwUEADNIYQ56w-_s',
    appId: '1:1073180398990:ios:e7e67134d21ec8fb7700df',
    messagingSenderId: '1073180398990',
    projectId: 'peerpedia-777a2',
    storageBucket: 'peerpedia-777a2.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBut1jf80ZyGX840VcuwUEADNIYQ56w-_s',
    appId: '1:1073180398990:ios:e7e67134d21ec8fb7700df',
    messagingSenderId: '1073180398990',
    projectId: 'peerpedia-777a2',
    storageBucket: 'peerpedia-777a2.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7aJAAFNFQkC_ut04JXvWFkyw4N6QZbsQ',
    appId: '1:1073180398990:web:bab3f9ee5e72eac47700df',
    messagingSenderId: '1073180398990',
    projectId: 'peerpedia-777a2',
    authDomain: 'peerpedia-777a2.firebaseapp.com',
    storageBucket: 'peerpedia-777a2.appspot.com',
  );
}
